const CATEGORY_WORDS: Record<string, readonly string[]> = {
  Nome: [
    "Abel",
    "Ana",
    "António",
    "Bento",
    "Bruna",
    "Bruno",
    "Carla",
    "Carlos",
    "Daniel",
    "Diana",
    "Eduardo",
    "Eva",
    "Fátima",
    "Fernando",
    "Gabriel",
    "Helena",
    "Inês",
    "João",
    "José",
    "Laura",
    "Luís",
    "Manuel",
    "Maria",
    "Nelson",
    "Olga",
    "Paulo",
    "Pedro",
    "Rosa",
    "Sofia",
    "Teresa",
    "Vítor",
  ],
  País: [
    "África do Sul",
    "Alemanha",
    "Angola",
    "Argentina",
    "Austrália",
    "Bélgica",
    "Brasil",
    "Cabo Verde",
    "Camarões",
    "Canadá",
    "Chile",
    "China",
    "Dinamarca",
    "Egito",
    "Espanha",
    "Estados Unidos",
    "Etiópia",
    "França",
    "Gana",
    "Guiné",
    "Índia",
    "Itália",
    "Japão",
    "Marrocos",
    "México",
    "Moçambique",
    "Namíbia",
    "Nigéria",
    "Noruega",
    "Países Baixos",
    "Portugal",
    "Quénia",
    "Reino Unido",
    "Rússia",
    "São Tomé e Príncipe",
    "Senegal",
    "Suécia",
    "Suíça",
    "Tanzânia",
    "Uganda",
    "Venezuela",
    "Zâmbia",
    "Zimbábue",
  ],
  Comida: [
    "Arroz",
    "Bacalhau",
    "Banana",
    "Bife",
    "Bolo",
    "Cachupa",
    "Calulu",
    "Carne",
    "Churrasco",
    "Feijão",
    "Funge",
    "Gelado",
    "Hambúrguer",
    "Kizaca",
    "Lasanha",
    "Mandioca",
    "Moamba",
    "Mufete",
    "Ovos",
    "Pão",
    "Pizza",
    "Quiabo",
    "Salada",
    "Sopa",
  ],
  Profissão: [
    "Advogado",
    "Arquitecto",
    "Bombeiro",
    "Cabeleireiro",
    "Camionista",
    "Cantor",
    "Dentista",
    "Enfermeiro",
    "Engenheiro",
    "Farmacêutico",
    "Fotógrafo",
    "Jornalista",
    "Médico",
    "Motorista",
    "Padeiro",
    "Professor",
    "Programador",
    "Psicólogo",
    "Secretário",
    "Taxista",
    "Veterinário",
  ],
  Animal: [
    "Abelha",
    "Águia",
    "Antílope",
    "Baleia",
    "Burro",
    "Cabra",
    "Cão",
    "Cavalo",
    "Coelho",
    "Elefante",
    "Foca",
    "Galinha",
    "Gato",
    "Girafa",
    "Hipopótamo",
    "Hiena",
    "Jacaré",
    "Leão",
    "Macaco",
    "Onça",
    "Pato",
    "Peixe",
    "Rato",
    "Rinoceronte",
    "Tigre",
    "Vaca",
    "Zebra",
  ],
  Cidade: [
    "Benguela",
    "Berlim",
    "Brasília",
    "Cabinda",
    "Cairo",
    "Cidade do Cabo",
    "Dundo",
    "Huambo",
    "Lisboa",
    "Lobito",
    "Luanda",
    "Lubango",
    "Malanje",
    "Maputo",
    "Mbanza Congo",
    "Namibe",
    "Nova Iorque",
    "Paris",
    "Porto",
    "Roma",
    "Saurimo",
    "Sumbe",
    "Tóquio",
    "Uíge",
  ],
  Música: [
    "Aleluia",
    "Amor",
    "Despacito",
    "Felicidade",
    "Hello",
    "Imagine",
    "Jerusalema",
    "Perfect",
    "Thriller",
    "Yesterday",
  ],
  Filme: [
    "Avatar",
    "Barbie",
    "Casablanca",
    "Dune",
    "Frozen",
    "Gladiador",
    "Inception",
    "Joker",
    "Matrix",
    "Oppenheimer",
    "Parasita",
    "Rocky",
    "Titanic",
  ],
};

export function normalizeAnswer(answer: string) {
  return answer
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLocaleLowerCase("pt-AO");
}

export function startsWithLetter(answer: string, letter: string) {
  return normalizeAnswer(answer).startsWith(normalizeAnswer(letter));
}

export function isKnownAnswer(category: string, answer: string) {
  const normalizedAnswer = normalizeAnswer(answer);

  return (CATEGORY_WORDS[category] ?? []).some(
    (word) => normalizeAnswer(word) === normalizedAnswer,
  );
}
